/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUserModal: typeof import('./components/user-group-comp/AddUserModal.vue')['default']
    BaseCronSelect: typeof import('./components/BaseCronSelect.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BasePagination: typeof import('./components/BasePagination.vue')['default']
    BatchForm: typeof import('./components/batch-form/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTransfer: typeof import('naive-ui')['NTransfer']
    RemoveButton: typeof import('./components/RemoveButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowOrEdit: typeof import('./components/ShowOrEdit.vue')['default']
    TagGroup: typeof import('./components/TagGroup.vue')['default']
    TopMenu: typeof import('./components/top-menu/index.vue')['default']
    UserSelector: typeof import('./components/user-selector/index.vue')['default']
    ViewComp: typeof import('./components/ViewComp.vue')['default']
  }
}
