spring:
  application:
    name: full-stack-test-hub
  jackson:
    time-zone: GMT+8
  datasource:
    hikari:
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      resolve-lazily: false
  profiles:
    active: dev

